# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: konrad.jelen@gmail.com
author_name: Stellars Henson
has_ai_rules: false
has_binder: false
has_settings: false
kind: frontend
labextension_name: jupyterlab_fold_all_code_extension
project_short_description: Jupyterlab extension to fold and expand all code cells,
    to help create nice notebook to share with non-technical audience
python_name: jupyterlab_fold_all_code_extension
repository: ''
test: true

